/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
import { Api } from './api'

export class Yapi extends Api {
  get swapTokens() {
    return this.ft.path('/swap-tokens').method('get').create()!
  }

  get swapToken() {
    return this.ft.path('/swap-token').method('get').create()!
  }

  get swapTokenPost() {
    return this.ft.path('/swap-token').method('post').create()!
  }

  get swapTokenDelete() {
    return this.ft.path('/swap-token').method('delete').create()!
  }

  get router() {
    return this.ft.path('/router').method('get').create()!
  }

  get routerPut() {
    return this.ft.path('/router').method('put').create()!
  }

  get routerPost() {
    return this.ft.path('/router').method('post').create()!
  }

  get routerDelete() {
    return this.ft.path('/router').method('delete').create()!
  }

  get routers() {
    return this.ft.path('/routers').method('get').create()!
  }

  get swapChainDetails() {
    return this.ft.path('/swap:chain-details').method('get').create()!
  }

  get swapPost() {
    return this.ft.path('/swap').method('post').create()!
  }

  get swapRebates() {
    return this.ft.path('/swap-rebates').method('get').create()!
  }

  get swapConfirmcallbackPost() {
    return this.ft.path('/swap:confirmcallback').method('post').create()!
  }

  get swapRecords() {
    return this.ft.path('/swap-records').method('get').create()!
  }

  get swapRecordPost() {
    return this.ft.path('/swap-record').method('post').create()!
  }

  get swapGas() {
    return this.ft.path('/swap:gas').method('get').create()!
  }

  get swapRecordConfirmPost() {
    return this.ft.path('/swap-record:confirm').method('post').create()!
  }

  get swapSummary() {
    return this.ft.path('/swap-summary').method('get').create()!
  }

  get swapConfirmPost() {
    return this.ft.path('/swap:confirm').method('post').create()!
  }

  get swapPreviewPost() {
    return this.ft.path('/swap:preview').method('post').create()!
  }
}
